### ISSUE TITLE
感谢，我在网上想找到这个

### ISSUE THREAD

**Issue by Xwudao** [FunnySaltyFish/ComposeDataSaver#2]
jetpack compose还算是比较新，资料还不算多。

比如，用户登录后的token如何保存，是我一直想的事情。

感觉该库还不错，用用看。

**Comment by FunnySaltyFish** [comment]
感谢支持。对于 token 这种全局情况，可以在 **单例 或 Activity** 级别的 ViewModel 中使用`mutableDataSaverState`托管。[我自己的项目](https://github.com/FunnySaltyFish/FunnyTranslation/blob/compose/base-core/src/main/java/com/funny/translation/AppConfig.kt)广泛用到了这个库，仅供参考。

**Comment by Xwudao** [comment]
> 感谢支持。对于 token 这种全局情况，可以在 **单例 或 Activity** 级别的 ViewModel 中使用`mutableDataSaverState`托管。[我自己的项目](https://github.com/FunnySaltyFish/FunnyTranslation/blob/compose/base-core/src/main/java/com/funny/translation/AppConfig.kt)广泛用到了这个库，仅供参考。

请教一下，如果token是要传给okhttp的，在header中是需要添加的，有什么优雅的方法吗？
token是登录后拿到的

**Comment by FunnySaltyFish** [comment]
可以为 OkHttp 添加拦截器
```kotlin
object UserConfig {
    var token by mutableDataSaverStateOf(DataSaverUtils, "key_user_token" , "")
}
...
OkHttpUtils -> 
private fun createBaseClient() = OkHttpClient().newBuilder().apply {
        // ......省略其它
        // 添加自定义请求头
        addInterceptor {
            val request = it.request()
            val builder = request.newBuilder()
            // 去除一些多余的 / 如 https://www.a.com///b -> https://www.a.com/b
            val newUrl = URL(removeExtraSlashOfUrl(request.url.toString())).also { url -> builder.url(url) }
            val domain = request.url.host

            // 访问某路径下的所有api均带上请求头-jwt
            if (newUrl.path.startsWith("api/v1/")){
                val jwt = UserConfig.token
                if (jwt != "") builder.addHeader("Authorization", "Bearer $jwt")
            }

            it.proceed(builder.build())
        }
}
```
供参考

**Comment by Xwudao** [comment]
@FunnySaltyFish 我知道用拦截器，我的意思是，你会如何存token，存到哪里？

首先，token是登录后获取到的，拦截器中如何获取到最新的token

是用mmkv吗？


谢谢！

**Comment by FunnySaltyFish** [comment]
或许我可以这样解释，这个库的目的是方便的将**以对Compose的State get/set的方式完成数据的持久化**，也就说，具体完成数据持久化（也就是把数据保存到哪里）是由其他框架完成的，我只是做了层包装。你给的`DataSaverInterface`才是指定保存方式。  
对于我，我是用`MMKV`做的具体存储，保存位置也就是mmkv的保存位置。对于上面的代码：
```kotlin
object UserConfig {
    var token by mutableDataSaverStateOf(DataSaverUtils, "key_user_token" , "")
}
```
当获取到最新的token时，使用`UserConfig.token = "你的token"`，框架会自动使用`MMKV`保存数据到本地，同时由于是`State`，其他使用到此`State`的`Composable`将可以检测到`State`的更改而做出相应更改；当杀死应用再打开时，`mutableDataSaverStateOf`会读取`MMKV`已保存到本地的值，设置为`State`的`value`。   
除了`MMKV`，还有框架默认的`Prefrence`和`DataStore`可以选择，或者参考`README`自己用其他的框架保存，都是可以的选择。

**Comment by Xwudao** [comment]
> 或许我可以这样解释，这个库的目的是方便的将**以对Compose的State get/set的方式完成数据的持久化**，也就说，具体完成数据持久化（也就是把数据保存到哪里）是由其他框架完成的，我只是做了层包装。你给的`DataSaverInterface`才是指定保存方式。 对于我，我是用`MMKV`做的具体存储，保存位置也就是mmkv的保存位置。对于上面的代码：
> 
> ```kotlin
> object UserConfig {
>     var token by mutableDataSaverStateOf(DataSaverUtils, "key_user_token" , "")
> }
> ```
> 
> 当获取到最新的token时，使用`UserConfig.token = "你的token"`，框架会自动使用`MMKV`保存数据到本地，同时由于是`State`，其他使用到此`State`的`Composable`将可以检测到`State`的更改而做出相应更改；当杀死应用再打开时，`mutableDataSaverStateOf`会读取`MMKV`已保存到本地的值，设置为`State`的`value`。 除了`MMKV`，还有框架默认的`Prefrence`和`DataStore`可以选择，或者参考`README`自己用其他的框架保存，都是可以的选择。

好的，谢谢
