### ISSUE TITLE
使用MMKV，但是compose preview提示先初始化MMKV

### ISSUE THREAD

**Issue by guozhiqiang123** [FunnySaltyFish/ComposeDataSaver#3]
如题，这个该怎么设置一下呀？
![image](https://user-images.githubusercontent.com/20378988/199237018-4d171e28-daae-4b60-95ae-bdbcf3c07404.png)

**Comment by FunnySaltyFish** [comment]
哦，这个初始化时 MMKV 框架自己要求的，你就在 `Application` 那里的 `onCreate` 调用 `MMKV.initialize` 即可
```
override fun onCreate() {
    super.onCreate();

    val rootDir = MMKV.initialize(this);
}
```

**Comment by FunnySaltyFish** [comment]
关于在 `@Preview` 使用的问题，建议只 Preview ·无状态、无参数的 `@Composable`。Preview 下似乎没法提供完整的 `CompositionLocal` 支持，而且我感觉 `Preview` 也没法模拟数据持久化的过程。要看此框架的效果还是建议 Run 一下，新项目也不会花很多时间

**Comment by guozhiqiang123** [comment]
> 

好的

**Comment by FunnySaltyFish** [comment]
那我就先把这个issue关啦，后续有其他问题欢迎交流
