### ISSUE TITLE
有写入的序列化，怎么没有读取的序列化呢？

### ISSUE THREAD

**Issue by guozhiqiang123** [FunnySaltyFish/ComposeDataSaver#4]
![image](https://user-images.githubusercontent.com/20378988/200157491-cc74b36c-c33b-4220-aa11-6bce5259ace6.png)

**Comment by FunnySaltyFish** [comment]
感谢指出，`ByteArray` 和 `Parcelable` 确实是写漏了。已补全相关代码和示例，并提交 commit。将在 `v1.1.2` 版本中发版。

**Comment by FunnySaltyFish** [comment]
`v1.1.3` 已发版，包含此项修复。此 issue 将被关闭，如有其余问题欢迎继续交流
