### ISSUE TITLE
再提个建议

### ISSUE THREAD

**Issue by guozhiqiang123** [FunnySaltyFish/ComposeDataSaver#5]
![image](https://user-images.githubusercontent.com/20378988/200226725-d1418f97-8f09-457a-9277-12d81464243e.png)
- 应该提供remove的方法
- 并且你的泛型设计上是非空的，比如存储Parcelable的时候，默认值一般不会手动去构造，而是传一个null，业务逻辑上再做判空处理。

**Comment by FunnySaltyFish** [comment]
1. remove 方法确实可以提供，我思索了下，会同时在 `DataSaverState` 中新增 `remove(new_value: T)` 方法，用于移除对应项并更新 `state` 的值，感谢建议
2. 非空的设计主要来源于，最早这个框架主要保存 `基本类型` ，我认为它们的默认值非 `null` 有助于减少异常的发生；你说的情况也确实合理，我再想想，后续应该会允许 `null` 值

**Comment by guozhiqiang123** [comment]
基础类型设计为非空的确有助于精简代码，减少非空判断。
你可以再提供一个@Composable，专门提供默认值和返回值都允许空的方法。

**Comment by guozhiqiang123** [comment]
另外，DataSaverMMKV我觉得没必要是普通class。可以直接搞成object class。这样不仅好初始化，而且在@Composable之外调用也比较简单。

**Comment by FunnySaltyFish** [comment]
有道理，我会综合考虑的

**Comment by FunnySaltyFish** [comment]
前段时间比较忙，我今天集中时间写了下，按你的建议变化如下
1. MMKV 的实现新增 `DefaultDataSaverMMKV` 变量，调用起来简单些（没有做 object 处理是因为要照顾到 `不同 mmkv` 的 需求）
2. 对 `registerTypeConverter` 的类型放宽了 `null` 的限制，现在自定义 Bean 可以设 null 的初值了（见 [示例](https://github.com/FunnySaltyFish/ComposeDataSaver/blob/master/app/src/main/java/com/funny/composedatasaver/ui/ExampleComposables.kt#L113) ）
3. 提供了 remove 方法
目前还未上传 jitpack，预估今晚做。这之前你有建议的话欢迎讨论，我再修改

**Comment by FunnySaltyFish** [comment]
v1.1.4 已发，有其他建议欢迎继续交流
