### ISSUE TITLE
【需求】让DataSaverState监听数据的变化

### ISSUE THREAD

**Issue by cy745** [FunnySaltyFish/ComposeDataSaver#6]
在使用的过程中发现一个问题，在设置页放了个Switcher开关，绑定上DataSaverState，用的好好的没问题。
但我还有一个新手引导页，同样放了个开关对接同一个Key但不是同一个DataSaverState，是想让用户尝试使用这个开关来看看效果，但是当用户修改状态了以后回到设置页，设置页里的这个开关还是没有修改。设置页本身是没有被recompose的，也就是DataSaverState实际没有更新。

这个问题简单来说就是目前DataSaverState不会监听数据持久层的变化，这个需求对我来说挺有用的，但似乎也不算是特别重要的东西，我也许可以试试看看能不能构思一个改进方案给你，可行的话就之后慢慢完善来

**Comment by FunnySaltyFish** [comment]
是的，目前不会监听数据的变化，目前我的解决方案是把类似的状态放到全局，各处引用同一个state，这样修改它的值所有地方都会同步更新，代码类似于 [这里](https://github.com/FunnySaltyFish/FunnyTranslation/blob/e9a666e9cd5b0b8931b5e65f918a181c6cedce4d/base-core/src/main/java/com/funny/translation/AppConfig.kt)。

当然，如果您有更好的方案（比如说我之前设想过的在 `DataSaverInterface` 中添加类似 `fun notifyDataChanged(key: String, newData: T): Flow<T>`，使数据变化时能被通知），也欢迎讨论和 PR ！

**Comment by cy745** [comment]
的确设置成全局的话能省很多工作，或许可以内部维护一个存放State的Map，添加一个参数控制该State是否全局唯一，根据参数确保这个Key只会创建一个State就行

但实际还是没有监听数据变化的逻辑，如果有其他更新数据的源，比如直接操作SharedPreference的情况

我觉得这个全局唯一State的这个逻辑算是另外一个改进的方向，我先试试弄这个监听数据变化的

**Comment by FunnySaltyFish** [comment]
五个月后，这个库加入了简单的支持（虽然你早已经自己实现了~）。此 Issue 关闭了，有好的想法的话欢迎之后继续交流~
