### ISSUE TITLE
DataSaverProperties 支持传入字符编码

### ISSUE THREAD

**Issue by ghost** [FunnySaltyFish/ComposeDataSaver#8]
IDEA生成的是UTF-8, 而打包出来的使用的却是ANSI(GBK/GB2312), 这会导致在配置文件相同时, IDEA运行/成品运行总有一个是乱码
![e9f2b9c8ef8d1a243e51b7aee623a50e](https://github.com/user-attachments/assets/96839a5c-6bb5-4201-bdd7-48075f8cc008)

**Comment by FunnySaltyFish** [comment]
好的，感谢指出。

目前此问题可以通过指定打包的编码来解决
```kotlin
nativeDistributions {
    // 加上 -Dfile.encoding=UTF-8，
    jvmArgs += listOf("-Dfile.encoding=UTF-8")
}
```

顺带一提，这个项目主要存的是Key-Value键值对。如果想存对话数据，建议还是使用数据库，比如 SqlDelight。你或许可以参考我的项目 https://github.com/FunnySaltyFish/Transtation-KMP/ 使用。里面也有对话页面

**Comment by ghost** [comment]
> 好的，感谢指出。
> 
> 目前此问题可以通过指定打包的编码来解决
> 
> ```kotlin
> nativeDistributions {
>     // 加上 -Dfile.encoding=UTF-8，
>     jvmArgs += listOf("-Dfile.encoding=UTF-8")
> }
> ```
> 
> 顺带一提，这个项目主要存的是Key-Value键值对。如果想存对话数据，建议还是使用数据库，比如 SqlDelight。你或许可以参考我的项目 https://github.com/FunnySaltyFish/Transtation-KMP/ 使用。里面也有对话页面

感谢建议, 后续也的确会转到数据库(目前因为时间问题先用的KV存消息, 且项目处于demo阶段主打一个能用就行)
